# Generated by Django 3.2 on 2021-04-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('current_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=8)),
                ('transaction_amount', models.FloatField()),
                ('wallet_opening_bal', models.FloatField()),
                ('wallet_closing_bal', models.FloatField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_of_user', to='wallet_app.wallet')),
            ],
        ),
    ]
